name: Github Activity

on:
  workflow_dispatch:
  schedule:
    # Runs every first and 6 hrs.
    - cron: "0 */12 * * *"

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Add activity to readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
